<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>560ffbcb-d9e0-4d3a-9a46-2309d38a5b30</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MqttServices.Core\MqttServices.Core.csproj" />
  </ItemGroup>
</Project>